$(function(){
	$("div[id^='c_portalResGroupNavNew_main']").attr("loaded","true");
	$("div[id^='c_portalResGroupAtlas_category']").attr("loaded","true");
	$("div[id^='c_portalResGroupEbizads_banner']").attr("loaded","true");	
	$("div[id^='c_portalResGroupNewsNew_list']").attr("loaded","true");	
	$("div[id^='c_portalResGroupColumn_detail']").attr("loaded","true");	
  $("div[id^='c_portalResGroupIntroNew_relatedlist']").attr("loaded","true");
  $("div[id^='c_portalResGroupNewsNew_detail']").attr("loaded","true");
});